import images from "./images";

const data = {
  flowers: [
    {
      name: 'Alstroemeria',
      id: 34522,
    },
    {
      name: 'Chamomile',
      id: 56311,
    },
    {
      name: 'Gypsophila',
      id: 99274,
    },
    {
      name: 'Anthurium',
      id: 75314,
    },
    {
      name: 'Astilbe',
      id: 84652,
    },
    {
      name: 'Dianthus',
      id: 72552,
    },
    {
      name: 'Rose',
      id: 12457,
    },
    {
      name: 'Eustoma',
      id: 99997,
    },
    {
      name: 'Asparagus',
      id: 34812,
    },
    {
      name: 'Chrysanthemum',
      id: 81956,
    },
    {
      name: 'Carnation',
      id: 10670,
    },
    {
      name: 'Astrantia',
      id: 19553,
    },
    {
      name: 'Peony',
      id: 51922,
    },
    {
      name: 'Astrophytum',
      id: 12953,
    },
    {
      name: 'Acidanthera',
      id: 21122,
    },
    {
      name: 'Bacopa',
      id: 24625,
    },
    {
      name: 'Cornflower',
      id: 39991,
    },
    {
      name: 'Veronica',
      id: 39993,
    },
    {
      name: 'Lisianthus',
      id: 39211,
    },
    {
      name: 'Bonsai',
      id: 39219,
    },
    {
      name: 'Gardenia',
      id: 18528,
    },
    {
      name: 'Dahlia',
      id: 26592,
    },
    {
      name: 'Hypoestes',
      id: 18335,
    },
    {
      name: 'Hydrangea',
      id: 35113,
    },
    {
      name: 'Hymorphotheca',
      id: 28812,
    },
    {
      name: 'Hypericum',
      id: 41311,
    },
    {
      name: 'Freesia',
      id: 38564,
    },
    {
      name: 'Silva Pink',
      id: 41535,
    },
    {
      name: 'Ozomanthus',
      id: 12385,
    },
    {
      name: 'Jasmine',
      id: 21833,
    },
    {
      name: 'Iris',
      id: 23411,
    },
    {
      name: 'Calibrachoa',
      id: 41231,
    },
    {
      name: 'Coleus',
      id: 21522,
    },
    {
      name: 'Lily',
      id: 12991,
    },
    {
      name: 'Magnolia',
      id: 15666,
    },
    {
      name: 'Narcissus',
      id: 12888,
    },
    {
      name: 'Nerine',
      id: 21882,
    },
    {
      name: 'Equalipt',
      id: 22199,
    },
    {
      name: 'Lilac',
      id: 28555,
    },
    {
      name: 'Tulip',
      id: 28814,
    },
    {
      name: 'Sunflower',
      id: 21413,
    },
    {
      name: 'Eringium',
      id: 12511,
    },
    {
      name: 'Wax',
      id: 28128,
    },
    {
      name: 'Matiola',
      id: 28105,
    },
    {
      name: 'Calla',
      id: 12877,
    },
    {
      name: 'Statica',
      id: 23412,
    },
    {
      name: 'Orchid',
      id: 12177,
    },
    {
      name: 'Lavender',
      id: 37667,
    },
  ],
  products: [
    {
      id: 'FMAA1S',
      name: 'Alstroemeria',
      format: 'bouquet',
      categories: ['soft', 'pink', 'mono'],
      rating: 7.6,
      feature: '',
      price: 2000,
      src: images.products.product1,
      flowers_id: [34522],
      reviews: [
        {
          star: 5,
          text: 'Очень понравился букет, собран на уровне моей 10-илетней сестры, которая не брезгается лезть в самые дебри за цветками, чтобы собрать хороший букет. Впечатляет!',
          reviewer_name: 'Василий',
          review_date: new Date('October 10, 2021'),
        },
      ],
    },
    {
      id: 'BQZ9W8',
      name: 'Merida',
      format: 'bouquet',
      categories: ['soft', 'light', 'mixed', 'chamomile', 'vase', 'collecto'],
      rating: 6.9,
      feature: '',
      price: 4500,
      src: images.products.product2,
      flowers_id: [34522, 56311],
      reviews: [],
    },
    {
      id: 'Y1JB95',
      name: 'Wedding bouquet "Budapesht"',
      format: 'bouquet',
      categories: ['soft', 'light', 'gypsophila', 'orange', 'pink', 'holiday', 'collecto'],
      rating: 8.5,
      feature: 'sale',
      price: 5500,
      actualPrice: 6000,
      src: images.products.product3,
      flowers_id: [34522, 12457, 99274],
      reviews: [
        {
          star: 5,
          text: 'Очаровал свою невесту этим букетом, аж отказалась приглашать своих пакостных родственников к себе на свадьбу. Спасибо!',
          reviewer_name: 'Дмитрий',
          review_date: new Date('March 5, 2022'),
        },
        {
          star: 4,
          text: 'Хотела купить маме, но цена слишком большая. Купила по скидке за накопленные карманные деньги. Теперь я на нуле, заебато',
          reviewer_name: 'Василиса',
          review_date: new Date('December 5, 2021')
        },
      ],
    },
    {
      id: 'HFVARV',
      name: 'Ballerina',
      format: 'bouquet',
      categories: ['mixed', 'soft', 'light', 'gypsophila', 'vase', 'composition', 'collecto'],
      rating: 8.1,
      feature: '',
      price: 4000,
      src: images.products.product4,
      flowers_id: [99274, 75314, 84652, 12457, 12385, 72552],
      reviews: [],
    },
    {
      id: 'T13DST',
      name: 'Love',
      format: 'bouquet',
      categories: ['mixed', 'soft', 'light', 'pink', 'chrysanthemum', 'collecto', 'holiday', 'composition', 'popular'],
      rating: 8.7,
      feature: '',
      price: 7200,
      src: images.products.product5,
      flowers_id: [34812, 81956, 10670, 12457],
      reviews: [
        {
          star: 5,
          text: 'Купил девушке, за которой бегал 2 года пока её парень водил её вокруг да около. Итог: дала',
          reviewer_name: 'Владимир',
          review_date: new Date('April 20, 2023')
        },
      ],
    },
    {
      id: '063NYB',
      name: 'Wind beneath the clouds',
      format: 'bouquet',
      categories: ['soft', 'light', 'pink', 'mono', 'popular'],
      rating: 8.7,
      feature: '',
      price: 15000,
      src: images.products.product6,
      flowers_id: [51922, 19553],
      reviews: [
        {
          star: 5,
          text: 'Женщина в чёрной маечке, которая держит цветок мне дала в тот же день. Отныне я не вёрджин. 5 звёзд из 5-и!',
          reviewer_name: 'Васёк',
          review_date: new Date('October 22, 2022'),
        },
        {
          star: 4,
          text: 'Не пожалел денег на дорогой букет, ибо у него были рейтинги хорошие. Результатом более-менее доволен, но 15к эта хрень не стоит. 4 звезды, и то с огроменной натяжкой...',
          reviewer_name: 'Дмитрий',
          review_date: new Date('March 11, 2023'),
        },
      ],
    },
    {
      id: 'P2YRDJ',
      name: 'Astrophytum in a pot',
      format: 'vase',
      categories: ['yellow', 'green', 'vase', 'dried'],
      rating: 6.7,
      feature: '',
      price: 450,
      src: images.products.product7,
      flowers_id: [12953],
      reviews: [],
    },
    {
      id: 'KIMC7C',
      name: 'Acidanthera',
      format: 'vase',
      categories: ['white', 'light',],
      rating: 6.9,
      feature: '',
      price: 350,
      src: images.products.product8,
      flowers_id: [21122],
      reviews: [],
    },
    {
      id: 'X65GJL',
      name: 'Bacopa',
      format: 'basket',
      categories: ['white', 'light', 'mono', 'popular'],
      rating: 7.7,
      feature: 'new',
      price: 1000,
      src: images.products.product9,
      flowers_id: [24625],
      reviews: [
        {
          star: 5,
          text: 'Оставил корзину с цветками рядом со своей консолью PlayStatiion 5, подходит по цвету и стилю',
          reviewer_name: 'Дмитрий',
          review_date: new Date('April 10, 2023'),
        },
      ],
    },
    {
      id: 'FW72RE',
      name: 'Basket of cornflowers',
      format: 'basket',
      categories: ['soft', 'blue', 'mono'],
      rating: 6.4,
      feature: '',
      price: 300,
      src: images.products.product10,
      flowers_id: [39991],
      reviews: [],
    },
    {
      id: 'GUEHRY',
      name: 'Yennefer',
      format: 'bouquet',
      categories: ['soft', 'mixed', 'pink', 'violet', 'yellow', 'collecto', 'composition'],
      rating: 7.9,
      feature: '',
      price: 8000,
      src: images.products.product11,
      flowers_id: [34522, 12457, 39993, 39211],
      reviews: [
        {
          star: 5,
          text: 'Восхитительный букет, меня не выкинули на море, а это о многом говорит)',
          reviewer_name: 'Геральт',
          review_date: new Date('April 2, 1272'),
        },
      ],
    },
    {
      id: 'CMD3M2',
      name: 'Manebu',
      format: 'box',
      categories: ['green', 'vase', 'dried'],
      rating: 8.0,
      feature: '',
      price: 12500,
      src: images.products.product12,
      flowers_id: [39219],
      reviews: [
        {
          star: 3,
          text: 'Качество пососное, само деревцо приехало местами сломанное',
          reviewer_name: 'Джинн',
          review_date: new Date('April 12, 2019'),
        },
      ],
    },
    {
      id: '1K7JAC',
      name: 'Bouquet "Pink Beauty"',
      format: 'bouquet',
      categories: ['soft', 'pink', 'mono', 'popular'],
      rating: 8.3,
      feature: '',
      price: 4300,
      src: images.products.product13,
      flowers_id: [18528],
      reviews: [
        {
          star: 5,
          text: 'Это самый красивый букет из всего ассортимента на сайте!',
          reviewer_name: 'Глеб',
          review_date: new Date('October 30, 2022'),
        },
        {
          star: 5,
          text: 'Моя сестра любит Хэллоу Китти и всё розовое, ей понравилось.',
          reviewer_name: 'Владислав',
          review_date: new Date('May 21, 2022'),
        },
      ],
    },
    {
      id: 'UDKGTR',
      name: 'Georgin',
      format: 'bouquet',
      categories: ['soft', 'light', 'white', 'pink', 'red', 'mixed', 'mono', 'composition', 'popular'],
      rating: 8.8,
      feature: '',
      price: 3500,
      src: images.products.product14,
      flowers_id: [26592],
      reviews: [
        {
          star: 5,
          text: 'Цвета выбраны классно',
          reviewer_name: 'Стас',
          review_date: new Date('August 3, 2023'),
        },
      ],
    },
    {
      id: '7M3XV3',
      name: 'Hypoestes',
      format: 'vase',
      categories: ['pink', 'vase'],
      rating: 7.7,
      feature: '',
      price: 500,
      src: images.products.product15,
      flowers_id: [18335],
      reviews: [],
    },
    {
      id: 'EP3V1I',
      name: 'Love Letter',
      format: 'envelope',
      categories: ['pink', 'yellow', 'soft', 'light', 'mixed', 'envelope', 'mono', 'holiday', 'popular'],
      rating: 8.2,
      feature: '',
      price: 3000,
      src: images.products.product16,
      flowers_id: [12457],
      reviews: [
        {
          star: 5,
          text: 'Название говорит за себя, призналась в любви к подруге. Она восприняла как шутку, 1 звезда!',
          reviewer_name: 'Ангелина',
          review_date: new Date('April 6, 2023'),
        },
      ],
    },
    {
      id: 'EZ0M04',
      name: "Mother's Day",
      format: 'bouquet',
      categories: ['pink', 'blue', 'soft', 'light', 'collecto', 'holiday', 'composition', 'popular'],
      rating: 8.1,
      feature: '',
      price: 2100,
      src: images.products.product17,
      flowers_id: [35113, 72552],
      reviews: [
        {
          star: 5,
          text: 'Причина оценки - улыбка матери. Спасибо!',
          reviewer_name: 'April',
          review_date: new Date('May 26, 2023'),
        },
      ],
    },
    {
      id: 'A2OVVU',
      name: 'Dimorphic happy box',
      format: 'box',
      categories: ['white'],
      rating: 7.3,
      feature: '',
      price: 1100,
      src: images.products.product18,
      flowers_id: [28812],
      reviews: [],
    },
    {
      id: 'XDIN8H',
      name: 'Heart of Woman',
      format: 'bouquet',
      categories: ['soft', 'light', 'pink', 'mixed', 'collecto', 'holiday', 'composition', 'popular'],
      rating: 7.7,
      feature: 'sale',
      price: 4100,
      actualPrice: 4500,
      src: images.products.product19,
      flowers_id: [12385, 41535, 38564, 12457, 35113, 41311],
      reviews: [],
    },
    {
      id: 'HSUWQ8',
      name: 'Jasmine',
      format: 'box',
      categories: ['soft', 'white', 'vase', 'mono'],
      rating: 8.0,
      feature: '',
      price: 4000,
      src: images.products.product20,
      flowers_id: [21833],
      reviews: [],
    },
    {
      id: 'ID2QR5',
      name: 'Iris wedding boquet',
      format: 'bouquet',
      categories: ['soft', 'violet', 'white', 'mixed', 'collecto', 'holiday'],
      rating: 7.0,
      feature: 'new',
      price: 3750,
      src: images.products.product21,
      flowers_id: [23411, 38564, 12457],
      reviews: [
        {
          star: 1,
          text: 'Жалею, что поженился, извиняюсь, но мне нужно где-то выплескнуть обиду',
          reviewer_name: 'Чёрт',
          review_date: new Date('Septemer 6, 2022'),
        },
      ],
    },
    {
      id: 'PS20OX',
      name: 'Calibrachoa',
      format: 'vase',
      categories: ['violet', 'vase'],
      rating: 6.0,
      feature: '',
      price: 250,
      src: images.products.product22,
      flowers_id: [41231],
      reviews: [],
    },
    {
      id: 'FFX3CW',
      name: 'Coleus',
      format: 'vase',
      categories: ['green', 'vase'],
      rating: 7.0,
      feature: '',
      price: 300,
      src: images.products.product23,
      flowers_id: [21522],
      reviews: [],
    },
    {
      id: '9VBO6O',
      name: 'Roses and lilies',
      format: 'bouquet',
      categories: ['soft', 'light', 'pink', 'mixed', 'holiday'],
      rating: 7.8,
      feature: 'sale',
      price: 2000,
      actualPrice: 2500,
      src: images.products.product24,
      flowers_id: [12991, 12457],
      reviews: [],
    },
    {
      id: 'WS4T8X',
      name: 'Joy of Everyday',
      format: 'bouquet',
      categories: ['soft', 'mixed', 'red', 'pink', 'collecto', 'composition', 'popular'],
      rating: 8.1,
      feature: 'new',
      price: 3500,
      src: images.products.product25,
      flowers_id: [15666, 12457, 72552],
      reviews: [],
    },
    {
      id: '596EQ0',
      name: 'Beauty of Narcissus',
      format: 'bouquet',
      categories: ['soft', 'light', 'yellow', 'mono', 'popular'],
      rating: 8.1,
      feature: '',
      price: 4750,
      src: images.products.product26,
      flowers_id: [12888],
      reviews: [
        {
          star: 5,
          text: 'Обожаю видеть радость и улыбки близких. Благодарю вас от всей души!',
          reviewer_name: 'Максим',
          review_date: new Date('June 13, 2023'),
        },
        {
          star: 5,
          text: 'Рад пользоваться вашими услугами, ваши курьеры всегда добры и жизнерадостны. Наверное получают достаточно. Кстати, можно к вам устроиться на работу?',
          reviewer_name: 'Алексей',
          review_date: new Date('July 29, 2023'),
        },
      ],
    },
    {
      id: '56DTQA',
      name: 'Rose Misery',
      format: 'bouquet',
      categories: ['soft', 'light', 'yellow', 'pink', 'mixed', 'collecto'],
      rating: 7.9,
      feature: '',
      price: 11000,
      src: images.products.product27,
      flowers_id: [12457, 28477, 22199, 21882],
      reviews: [],
    },
    {
      id: 'BY2GLE',
      name: 'On the lilac moon',
      format: 'bouquet',
      categories: ['soft', 'light', 'violet', 'mono', 'popular'],
      rating: 7.9,
      feature: '',
      price: 750,
      src: images.products.product28,
      flowers_id: [28555],
      reviews: [],
    },
    {
      id: '0WXWZP',
      name: '11 tulips',
      format: 'bouquet',
      categories: ['soft', 'light', 'violet', 'mono', 'popular'],
      rating: 8.0,
      feature: '',
      price: 3250,
      src: images.products.product29,
      flowers_id: [28814],
      reviews: [],
    },
    {
      id: 'TYASS3',
      name: 'Harmony',
      format: 'bouquet',
      categories: ['soft', 'light', 'yellow', 'blue', 'mixed', 'composition', 'collecto', 'holiday'],
      rating: 8.0,
      feature: '',
      price: 5000,
      src: images.products.product30,
      flowers_id: [28128, 22199, 12511, 21413],
      reviews: [
        {
          star: 4,
          text: 'Подсолнухи завяли к моменту получения букета. Но я не растерялся и просто убрал их. Без обид, но отнимаю звезду за проёб.',
          reviewer_name: 'Виталий',
          review_date: new Date('September 2, 2022'),
        },
      ],
    },
    {
      id: 'WYSAUF',
      name: 'Composition «Angelique»',
      format: 'hatbox',
      categories: ['soft', 'light', 'composition', 'pink', 'mono', 'roses'],
      rating: 7.2,
      feature: '',
      price: 4000,
      src: images.products.product31,
      flowers_id: [12457],
      reviews: [],
    },
    {
      id: 'D1T71U',
      name: 'Bouquet «Haley»',
      format: 'bouquet',
      categories: ['soft', 'light', 'orange', 'mono', 'roses'],
      rating: 8.9,
      feature: 'sale',
      price: 3000,
      actualPrice: 3500,
      src: images.products.product32,
      flowers_id: [12457, 22199],
      reviews: [
        {
          star: 5,
          text: 'Ляпота!',
          reviewer_name: 'Виктор',
          review_date: new Date('September 12, 2022'),
        },
        {
          star: 5,
          text: '',
          reviewer_name: 'Диана',
          review_date: new Date('July 11, 2023'),
        },
        {
          star: 5,
          text: 'Моё сердце наполнено счастьем, это лучшие моменты моей жизни. Оставлю ли я свой отзыв? Конечно!',
          reviewer_name: 'Антон',
          review_date: new Date('August 7, 2022'),
        },
      ],
    },
    {
      id: '4BZZQQ',
      name: 'pink alstroemerias in a hatbox',
      format: 'hatbox',
      categories: ['soft', 'light', 'pink', 'mono', 'holiday', 'popular'],
      rating: 8.3,
      feature: '',
      price: 4250,
      src: images.products.product33,
      flowers_id: [34522],
      reviews: [],
    },
    {
      id: '9FN7L6',
      name: 'Heaven Message',
      format: 'bouquet',
      categories: ['soft', 'light', 'blue', 'chrysanthemum', 'mono', 'holiday', 'composition', 'popular'],
      rating: 8.3,
      feature: '',
      price: 2150,
      src: images.products.product34,
      flowers_id: [81956],
      reviews: [
        {
          star: 5,
          text: 'В жизни ничего красивее не видел..',
          reviewer_name: 'Андрей',
          review_date: new Date('May 17, 2023'),
        },
      ],
    },
    {
      id: 'NZ8ZYT',
      name: 'Comosition «Pandora»',
      format: 'basket',
      categories: ['composition', 'soft', 'light', 'mixed', 'pink', 'blue', 'collecto', 'holiday'],
      rating: 7.7,
      feature: '',
      price: 12500,
      src: images.products.product35,
      flowers_id: [12457, 28105, 22199, 10670, 39211, 35113],
      reviews: [],
    },
    {
      id: '64K8GK',
      name: 'Rainbow',
      format: 'bouquet',
      categories: ['light', 'gypsophila', 'mixed', 'mono', 'holiday', 'popular'],
      rating: 8.7,
      feature: '',
      price: 4000,
      src: images.products.product36,
      flowers_id: [99274],
      reviews: [
        {
          star: 5,
          text: 'Подарила это своей девушке. Символично и красиво)',
          reviewer_name: 'Афродита',
          review_date: new Date('January 18, 2023'),
        },
        {
          star: 5,
          text: 'Отличный сервис, благодаря которому я сохранила свои отношения, подарила этой дуре на 8-ое марта. Привезли за 15 минут',
          reviewer_name: 'Ольга',
          review_date: new Date('March 9, 2023'),
        },
      ],
    },
    {
      id: 'HP12HI',
      name: 'Gentle compliment',
      format: 'bouquet',
      categories: ['soft', 'mixed', 'pink', 'violet', 'mono', 'roses'],
      rating: 8.1,
      feature: '',
      price: 3500,
      src: images.products.product37,
      flowers_id: [12457, 22199],
      reviews: [],
    },
    {
      id: 'O5RCN9',
      name: 'Bouquet «Darling»',
      format: 'bouquet',
      categories: ['light', 'soft', 'pink', 'mono', 'popular'],
      rating: 8.1,
      feature: 'sale',
      price: 8500,
      actualPrice: 9000,
      src: images.products.product38,
      flowers_id: [51922, 22199],
      reviews: [],
    },
    {
      id: 'ERXPB8',
      name: 'Affectionate look',
      format: 'bouquet',
      categories: ['light', 'soft', 'white', 'mono', 'composition'],
      rating: 8.1,
      feature: '',
      price: 4000,
      src: images.products.product39,
      flowers_id: [12877, 22199],
      reviews: [],
    },
    {
      id: '87B0V0',
      name: 'Message from Butterflies',
      format: 'envelope',
      categories: ['soft', 'envelope', 'pink', 'mixed', 'chrysanthemum', 'collecto', 'holiday'],
      rating: 6.8,
      feature: '',
      price: 3500,
      src: images.products.product40,
      flowers_id: [12457, 22199, 72552, 81956, 41311, 23412],
      reviews: [],
    },
    {
      id: 'L4U579',
      name: 'Nord Verona',
      format: 'bouquet',
      categories: ['soft', 'mixed', 'blue', 'white', 'pink', 'mono', 'composition', 'popular'],
      rating: 8.8,
      feature: '',
      price: 2850,
      src: images.products.product41,
      flowers_id: [35113],
      reviews: [
        {
          star: 5,
          text: 'Подарил своей единственной неповторимой матери, ибо она этого заслуживает. Благодарю вас за услугу!',
          reviewer_name: 'Эдуард',
          review_date: new Date('September 18, 2022'),
        },
        {
          star: 5,
          text: '',
          reviewer_name: 'Вадим',
          review_date: new Date('March 1, 2023'),
        },
      ],
    },
    {
      id: '4L5QFC',
      name: 'Nord Verona XL',
      format: 'bouquet',
      categories: ['soft', 'mixed', 'blue', 'white', 'pink', 'mono', 'composition'],
      rating: 8.2,
      feature: '',
      price: 7000,
      src: images.products.product42,
      flowers_id: [35113],
      reviews: [],
    },
    {
      id: '4JC6FM',
      name: 'Smile',
      format: 'bouquet',
      categories: ['soft', 'light', 'pink', 'mono', 'popular'],
      rating: 6.6,
      feature: '',
      price: 4000,
      src: images.products.product43,
      flowers_id: [10670],
      reviews: [],
    },
    {
      id: 'AA1SBQ',
      name: 'Cherry Blossom',
      format: 'hatbox',
      categories: ['soft', 'light', 'pink', 'red', 'mixed', 'collecto', 'composition'],
      rating: 7.7,
      feature: '',
      price: 5250,
      src: images.products.product44,
      flowers_id: [12177, 99997, 12457],
      reviews: [],
    },
    {
      id: 'Z9W8Y1',
      name: 'Mia',
      format: 'bouquet',
      categories: ['soft', 'light', 'mixed', 'white', 'pink', 'collecto', 'composition'],
      rating: 8.5,
      feature: '',
      price: 5000,
      src: images.products.product45,
      flowers_id: [10670, 12177, 99997, 12457],
      reviews: [],
    },
    {
      id: 'JB95HF',
      name: 'Violet softness',
      format: 'bouquet',
      categories: ['violet', 'white', 'mixed', 'soft', 'mono'],
      rating: 7.4,
      feature: '',
      price: 4750,
      src: images.products.product46,
      flowers_id: [23411, 28814],
      reviews: [],
    },
    {
      id: 'VARVT1',
      name: 'Lavender coolness',
      format: 'bouquet',
      categories: ['violet', 'collecto', 'mono'],
      rating: 5.9,
      feature: '',
      price: 2100,
      src: images.products.product47,
      flowers_id: [37667],
      reviews: [],
    },
    {
      id: '3DST06',
      name: 'Tulips with Lavender',
      format: 'bouquet',
      categories: ['violet', 'pink', 'mixed', 'light', 'mono'],
      rating: 7.0,
      feature: '',
      price: 5500,
      src: images.products.product48,
      flowers_id: [37667, 37667],
      reviews: [],
    },
    {
      id: '3NYBP2',
      name: 'Orchids Ultramarine',
      format: 'bouquet',
      categories: ['violet', 'mono'],
      rating: 8.0,
      feature: '',
      price: 4500,
      src: images.products.product49,
      flowers_id: [12177],
      reviews: [],
    },
    {
      id: 'YRDJKI',
      name: 'Mono bouquet with 14 irises',
      format: 'bouquet',
      categories: ['violet', 'mono', 'popular'],
      rating: 7.1,
      feature: 'sale',
      price: 3250,
      actualPrice: 3500,
      src: images.products.product50,
      flowers_id: [23411],
      reviews: [],
    },
  ],

  categories: [
    {
      name: 'gypsophila',
      displayName: 'Bouquets of gypsophila',
    },
    {
      name: 'chamomile',
      displayName: 'Bouquets of daisies',
    },
    {
      name: 'chrysanthemum',
      displayName: 'Bouquets of chrysanthemums',
    },
    {
      name: 'vase',
      displayName: 'Indoor flowers in pots',
    },
    {
      name: 'mono',
      displayName: 'Mono bouquets',
    },
    {
      name: 'collecto',
      displayName: 'Prefabricated bouquets',
    },
    {
      name: 'holiday',
      displayName: 'Holiday bouquets',
    },
    {
      name: 'composition',
      displayName: 'Flower compositions',
    },
    {
      name: 'envelope',
      displayName: 'Envelopes',
    },
    {
      name: 'postcard',
      displayName: 'Postcards',
    },
    {
      name: 'present',
      displayName: 'Gifts',
    },
    {
      name: 'dried',
      displayName: 'Bouquets of dried flowers',
    },
    {
      name: 'balloons',
      displayName: 'Balloons',
    },
    {
      name: 'popular',
      displayName: 'Popular',
    },
    {
      name: 'roses',
      displayName: 'Bouquets of roses',
    },
    {
      name: 'funeral',
      displayName: 'Flowers for funerals',
    },
    {
      name: 'package',
      displayName: 'Gift package',
    },
  ],

  additional: [
    {
      name: 'fertilizer',
      title: 'Fertilizers for cut flowers',
      descr: 'If you indicate this in your wishes for the bouquet, we will include a bag of fertilizer for you.',
      price: 500,
    },
    {
      name: 'signature',
      title: 'sign the postcard',
      descr: 'In your wishes for the bouquet, indicate the text you want to place and select the card itself on the website/',
      price: 1,
    },
    {
      name: 'photo',
      title: 'Bouquet photosession',
      descr: 'Please indicate this in the notes to your order and we will send a photo of the finished bouquet before delivery. On holidays due to heavy workload this is not possible.',
      price: 250,
    },
    {
      name: 'surprise',
      title: 'Bouquet-surprise',
      descr: 'If you want the recipient not to know what he will be given and from whom, please indicate this in the notes to the order.',
      price: 750,
    },
  ],

  faq: [
    {
      title: 'WILL THE ORDERED BOUQUET EXACTLY CORRESPOND TO ITS PICTURE ON THE SITE?',
      descr: 'The bouquet is assembled according to an individual bouquet matrix. However, there may be cases when the required colors are not available or the available flowers differ from those shown in the photo, and with the approval of the customer they can be replaced with similar ones. Or, if the florist believes that these changes will not lead to a significant change in the image of the bouquet, then he can replace some of the flowers himself. And before sending, the photo is sent to the customer, who approves the resulting bouquet. Each flower is different from the other, just as each bouquet will be individual, but this is its charm... individuality.',
    },
    {
      title: 'HOW LONG DO BOUQUETS OF DRIED FLOWERS LAST?',
      descr: 'Bouquets of dried flowers can please the eye for a long time - from several months to several years. The duration of preservation depends on the care of handling, storage location and the quality of the dried flowers themselves. Observance of the right conditions can significantly prolong their attractiveness and freshness.',
    },
    {
      title: 'DO YOU TAKE A PHOTO OF THE READY BOUQUET BEFORE SHIPPING?',
      descr: 'Yes, of course, we are ready to provide you with a photo of the finished bouquet before sending it. We understand that it is important to have a clear idea of ​​what kind of bouquet will be delivered. This gives you the opportunity to see the bouquet in all its glory and make sure it meets your expectations. Our goal is to provide transparency and quality in every order.',
    },
    {
      title: 'HOW LONG SHOULD FLOWERS LAST IN A BOUQUET?',
      descr: 'The length of time that flowers in a bouquet can maintain their freshness depends on several factors, such as types of flowers, storage and care conditions. On average, the freshness of a bouquet can last from several days to two weeks. However, there are flowers that retain their freshness longer, for example, chrysanthemums, gerberas, alstroemeria, and lilies. Regularly trimming the stems, changing the water, and avoiding direct sunlight can help extend the life of your bouquet.',
    },
    {
      title: 'IS IT DELIVERY OUTSIDE THE MKAD?',
      descr: 'Yes, we provide a delivery service outside the Moscow Ring Road. We are pleased to offer convenient and reliable delivery to our customers to various locations, not limited to the Moscow region. Our team works to ensure that your bouquet reaches you safe and fresh, regardless of the distance.',
    },
    {
      title: 'HOW TO DETERMINE WHEN FLOWERS ARE FRESH?',
      descr: 'To determine the freshness of flowers, look at the petals and buds - they should be bright and without yellowing. The leaves should be green and without spots, and the smell should be pleasant. The stems should be strong, the water in the vase should be clean, and the stems should be cut at an angle. Avoid flowers with damaged petals or broken stems. These simple signs will help determine how fresh the flowers are.',
    },
    {
      title: 'WHAT IS THE DIFFERENCE BELARUSIAN ROSE FROM IMPORTED?',
      descr: 'The Belarusian rose grows in Belarus, which may affect its adaptation to local climatic conditions. Imported roses, on the other hand, grow in different countries with varying climates and soils. Therefore, Belarusian roses can have a certain uniqueness, and imported roses can be varied in colors, sizes and scents, depending on their origin.',
    },
  ],
}


export default data;